# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Neutronium' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Neutronium

  target 'Neutronium-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NeutroniumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Neutronium-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Neutronium-tvOS

  target 'Neutronium-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


# platform :ios, '11.3'

# target 'Neutronium' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   pod 'Firebase/Core'

#   # あとで必要に応じてコメントアウトを外す
#   # pod 'Firebase/AdMob'
#   # pod 'Firebase/Auth'
#   # pod 'Firebase/Crash'
#   # pod 'Firebase/Database'
#   # pod 'Firebase/DynamicLinks'
#   # pod 'Firebase/Performance'
#   # pod 'Firebase/Firestore'
#   # pod 'Firebase/Messaging'
#   # pod 'Firebase/RemoteConfig'
#   # pod 'Firebase/Storage'

# end